-- CreateTable
CREATE TABLE "Lead" (
    "id" SERIAL NOT NULL,
    "fullAddress" TEXT NOT NULL,
    "sector" TEXT NOT NULL,
    "city" TEXT,
    "groundFloorArea" DOUBLE PRECISION NOT NULL,
    "hasBasement" BOOLEAN NOT NULL,
    "basementArea" DOUBLE PRECISION,
    "hasUpperFloor" BOOLEAN NOT NULL,
    "upperFloorArea" DOUBLE PRECISION,
    "hasApartment" BOOLEAN NOT NULL,
    "apartmentArea" DOUBLE PRECISION,
    "occupancyStatus" TEXT NOT NULL,
    "annualRentExclCharges" DOUBLE PRECISION,
    "tenantActivity" TEXT,
    "leaseEndDate" TIMESTAMP(3),
    "annualCharges" DOUBLE PRECISION,
    "propertyTax" DOUBLE PRECISION,
    "commercialLeaseFile" TEXT,
    "propertyTaxFile" TEXT,
    "plansFile" TEXT,
    "photosFile" TEXT,
    "otherDocumentsFile" TEXT,
    "additionalInfo" TEXT,
    "ownerName" TEXT NOT NULL,
    "ownerPhone" TEXT NOT NULL,
    "ownerEmail" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Lead_pkey" PRIMARY KEY ("id")
);
